# Generated by Django 2.1.5 on 2019-01-06 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Despesa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.CharField(max_length=20, verbose_name='data de criacao')),
                ('tipo_despesa', models.CharField(choices=[('Remédio', 'Remédio'), ('Roupas', 'Roupas'), ('Alimentação', 'Alimentação'), ('Educação', 'Educação'), ('Transporte', 'Transporte'), ('Outros', 'Outros')], max_length=30, verbose_name='tipo de despesa')),
                ('descricao', models.TextField(max_length=100, verbose_name='descricao')),
                ('forma_pagamento', models.CharField(choices=[('Dinheiro', 'Dinheiro'), ('Cartão de Crédito', 'Cartão de Crédito'), ('Cartão de Débito', 'Cartão de Débito'), ('Cartão Crediário', 'Cartão Crediário'), ('Cheque', 'Cheque')], max_length=50, verbose_name='forma de pagamento')),
                ('vencimento', models.DateField()),
                ('quitado', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Despesa',
                'verbose_name_plural': 'Despesas',
                'ordering': ('-vencimento', 'forma_pagamento'),
            },
        ),
    ]
